### ISSUE TITLE
 This modified version not require 'scale' and 'rotation' parameters to render, why is that?

### ISSUE THREAD

**Issue by songofjoy** [dcharatan/diff-gaussian-rasterization-modified#1]
Hi, thanks for your great work. I have a few questions I don't understand. Why not use the 3DGaussian's diff-gaussian-rendering package directly.  This modified version not require 'scale' and 'rotation' parameters to render, why is that? Thank you!

**Comment by dcharatan** [comment]
The original `diff-gaussian-rasterization` package uses a different convention for the spherical harmonics. See [this comment](https://github.com/graphdeco-inria/gaussian-splatting/issues/176#issuecomment-1918708917) for more details. This modified version's API is exactly the same -- you can either pass precomputed covariance matrices or scale + rotation.
