### ISSUE TITLE
Difference

### ISSUE THREAD

**Issue by TwiceMao** [dcharatan/diff-gaussian-rasterization-modified#2]
@dcharatan  Hi,   I come from the pixelSplat  repository. Could you please be kind enough to tell me what the differences are between this renderer and the original one of 3D Gaussian Splatting?

**Comment by Mr-ind1fferent** [comment]
+1

**Comment by dcharatan** [comment]
You can see the diff here:
https://github.com/dcharatan/diff-gaussian-rasterization-modified/compare/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d..HEAD

TL;DR: The only modification is that the convention (order) of the spherical harmonics has been changed to match the e3nn library's convention.
